### ISSUE TITLE
Was GPL license intentional?

### ISSUE THREAD

**Issue by vitriolix** [ikkisoft/SerialKiller#1]
Seems like a potentially interesting and helpful library, but I'd expect this to be Apache or at least LGPL licensed.  Do you really intend this to be GPL?  This will prevent a vast majority of developers from being able to use this

**Comment by ikkisoft** [comment]
Totally agree. Since it was a weekend project, I didn't think about that.
I'm thinking to dual-license to Apache License 2.0.

I'll close this ticket once done, and updated all references.

**Comment by ikkisoft** [comment]
https://github.com/ikkisoft/SerialKiller/releases/tag/0.2
