### ISSUE TITLE
Exception does not distinguish between blacklist and non-whitelist blocking

### ISSUE THREAD

**Issue by haraldk** [ikkisoft/SerialKiller#10]
It is sometimes useful for client code to be able to distinguish between a blacklist match and a white-list non-match, as they may require quite different actions (ie. edit the whitelist or rewrite code to not rely on unsafe classes, or worse...). 

I suggest making the words "blacklist" and "non-whitelist" part of the exception message, as a low impact solution.

**Comment by ikkisoft** [comment]
In both _profiling_ and _blocking_ mode, the exception is displaying whether it worked on whitelist or blacklist. E.g. see https://github.com/ikkisoft/SerialKiller/blob/master/src/org/nibblesec/tools/SerialKiller.java#L85

**Comment by haraldk** [comment]
Yes, the *logging* shows it. However, the exception message does not. And I don't want to add log-parsing code to find out. ;-)
