### ISSUE TITLE
SerialKiller creates excessive logfiles if logging enabled

### ISSUE THREAD

**Issue by haraldk** [ikkisoft/SerialKiller#12]
The following code in SerailKiller's constructor is problematic, as it will create a new `FileHandler` (along with a new file) for each instance. It should probably be noted in the readme that this option is only recommended for single instances, and when profiling is enabled. 

````java
        if (config.isLogging()) {
            Handler fileHandler = new FileHandler(config.logFile(), true);
            LOGGER.addHandler(fileHandler);
            LOGGER.setLevel(Level.ALL);
        }
````

I'm thinking this code may be dropped entirely, and instead be left to user configuration, using the `java.util.logging.config.file` system property or `lib/logging.propertis` as described in the [LogManager API doc](https://docs.oracle.com/javase/7/docs/api/java/util/logging/LogManager.html).

Best regards,

-- 
Harald K

**Comment by ikkisoft** [comment]
Implemented. Going out with the next release (0.5). Thanks again @haraldk for all your improvements!!!
