### ISSUE TITLE
Package as agent or Byteman

### ISSUE THREAD

**Issue by jeffmaury** [ikkisoft/SerialKiller#5]
Should be fine if it would be provided as a Java agent or Byteman package so as to inject functionality into the JDK ObjectInputStream

**Comment by ikkisoft** [comment]
While using JVM-wide solutions applied as Java agent seem like a perfect idea, there are two drawbacks:
- In standard enterprise environments, developers cannot modify the startup scripts and don't have access to the JVM options 
- For performance and stability, it may not make sense to have an additional Java agent loaded in memory 

For an agent-based solution, look at https://github.com/Contrast-Security-OSS/contrast-rO0
