### ISSUE TITLE
Wrong/missing blacklist entries

### ISSUE THREAD

**Issue by mbechler** [ikkisoft/SerialKiller#6]
Not that I would count on the blacklist, but I think your entry for the spring vector is wrong.

The piece of code that gives the arbitrary method invocation that is needed is 

org.springframework.core.SerializableTypeWrapper$MethodInvokeTypeProvider

and not the ObjectFactory (that just conveniently supplies the instance to call upon). Certainly does not hurt to forbid that, too, but the MethodInvokeTypeProvider alone can ruin your day.

**Comment by ikkisoft** [comment]
Fixed. Thanks!
