### ISSUE TITLE
Proxy and InvocationHandler

### ISSUE THREAD

**Issue by h3xstream** [ikkisoft/SerialKiller#7]
Knowing that most of gadget relies on [Proxy](https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/Proxy.html) and [InvocationHandler](https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/InvocationHandler.html). Would it be possible to add those to the blacklist and look for implementation of InvocationHandler?

**Comment by ikkisoft** [comment]
Hi @h3xstream,

Proxy was already included in the config. I assume you saw the config in the readme, which is just an example. I will add a note to clarify.

As for the _InvocationHandler_ interface, I had some classes but I have now included all known implementations. See https://github.com/ikkisoft/SerialKiller/commit/867215cdf36d9dcb265f7cd5f816a0394640e78b

Cheers,
Luca

**Comment by h3xstream** [comment]
The proxy type should be sufficient indeed.

Quick note their are various implementations of InvocationHandler that are not in the JDK ([JdkDynamicAopProxy](https://docs.spring.io/spring/docs/1.1.4/javadoc-api/org/springframework/aop/framework/JdkDynamicAopProxy.html)).

**Comment by ikkisoft** [comment]
Yes, I know but the implementation of the blacklist doesn't support interfaces, thus I have specified all known instances of InvocationHandler. It's not ideal, but frankly black-listing isn't ideal either.
