### ISSUE TITLE
Threading issue/race condition

### ISSUE THREAD

**Issue by haraldk** [ikkisoft/SerialKiller#9]
Hi!

Thanks for creating this! 

However, during testing I've found some bugs. The static variables in `SerialKiller` that are assigned in constructor may cause serious race condition and confusing results, if using multiple configurations and multiple threads.

Consider the following test case:

````java
@Test(expected = InvalidClassException.class)
public void testThreadIssue() throws Exception {
    ByteArrayOutputStream bytes = new ByteArrayOutputStream();

    try (ObjectOutputStream stream = new ObjectOutputStream(bytes)) {
        stream.writeObject(42);
    }

    try (ObjectInputStream stream = new SerialKiller(new ByteArrayInputStream(bytes.toByteArray()), "src/test/resources/blacklist-all.conf")) { // Blacklist: .*
        // Create a dummy SK with different config
        new SerialKiller(new ByteArrayInputStream(bytes.toByteArray()), "src/test/resources/whitelist-all.conf"); // No blacklist and whitelist: .*

        stream.readObject(); // Now passing...

        fail("All should be blacklisted");
    }
}
````

PS: I'll be back with a PR later, fixing this. :-)

Best regards,

-- 
Harald K

**Comment by ikkisoft** [comment]
Hi Harald,

Yes, the current implementation is designed to allow a single instance of SerialKiller only. 

Without rules caching, even a single instance may be too slow on high-traffic production instances thus I didn't think it would make sense to allow multiple executions.

I think we should combine this issue with https://github.com/ikkisoft/SerialKiller/issues/4
